{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API Gateway Service (HTTP Requests Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"apigateway_service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loan Service (HTTP Requests Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"loan_service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Service (HTTP Requests Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"user_service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Book Service (HTTP Requests Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"book_service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}