services:
  app:
    build: .
    container_name: userservice-app
    ports:
      - "$APP_PORT:8080"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - userservice_net
  db:
    image: postgres:17.2-alpine
    container_name: userservice-db
    ports:
      - "54322:5432"
    environment:
      POSTGRES_DB: $BOOKSERVICE_DB_NAME
      POSTGRES_USER: $BOOKSERVICE_DB_USER
      POSTGRES_PASSWORD: $BOOKSERVICE_DB_PASS
    volumes:
      - userservice_db_data:/var/lib/postgresql/data
      - ./data:/data
    networks:
      - userservice_net

volumes:
  userservice_db_data:


networks:
  userservice_net:
    driver: bridge
