services:
  app:
    build: .
    container_name: loanservice-app
    ports:
      - "$APP_PORT:8082"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - loanservice_net
  db:
    image: postgres:17.2-alpine
    container_name: loanservice-db
    ports:
      - "54324:5432"
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - loanservice_db_data:/var/lib/postgresql/data
      - ./data:/data
    networks:
      - loanservice_net

volumes:
  loanservice_db_data:


networks:
  loanservice_net:
    driver: bridge
